### ISSUE TITLE
환생의 불꽃 창 제작

### ISSUE THREAD

**Issue by 0407chan** [0407chan/web-maple#54]
- 환불창을 만들어보자
### 참고 URL
- 추옵 확률표 https://namu.wiki/w/%EC%B6%94%EA%B0%80%EC%98%B5%EC%85%98#s-3.1
- 단일스텟, 이중스텟 https://namu.wiki/w/%EC%B6%94%EA%B0%80%EC%98%B5%EC%85%98#s-6.3

### TODO
- [x] 영환불로 아이템에 추옵 줄 수 있음
- [x] 강환불로 추옵 줄 수 있음
- [x] 영환불 확률표 적용하기
- [x] 강환불 확률표 적용하기
- [x] 환불 창에서 사용하는 slot을 진짜 해당 equip, inven slot 복사해온 후, equip, inven에도 적용해줘야함
- [x] 환불 돌렸을 때 누적 개수 표기
- [ ] 환불 돌렸을 때 돌리는 이펙트 표기
- [ ] 돌려진 추옵이 각각 몇 추로 나온건지 표기
- [x] 원하는 유효옵 선택하면, 해당 옵션만 강조해서 표기해주기
- [x] 환불창에서 더블클릭하면 아이템 제거하기

### 2021. 09. 27 월 작업 중
![image](https://user-images.githubusercontent.com/19217576/134921623-93a6ad91-b253-4385-8c09-92e182c955be.png)

### 참고 이미지
![image](https://user-images.githubusercontent.com/19217576/134811042-3882b938-a7b0-407a-ac00-99f364d234a5.png)
